### ISSUE TITLE
Get clicked node

### ISSUE THREAD

**Issue by lmorel3** [atago0129/d3-v4-contextmenu#7]
Hi, and thanks for your library. 

I was just wondering if you can pass a reference to the clicked node when you trigger the item "action". Otherwise use cases are limited...

Is it possible?

**Comment by atago0129** [comment]
Hi, thanks your feedback.
I think it's exactly as you said. So I fix.
demo: http://plnkr.co/edit/i84SdzHnhKwHgZB21lpe?p=preview

... and sorry, I can't publish npm package now. Please wait just a little.

**Comment by lmorel3** [comment]
I tried to manually updated "dist" folder in node_modules, but it doesn't work. My action is quite simple : 
```
action: (d, i) => {
    console.log(d, i);
}
```
But d is always "undefined", and i equals 0.

Perhaps, I've data in my graph, which is something like this one [Collapsible tree diagram in v4
](https://bl.ocks.org/d3noob/43a860bc0024792f8803bba8ca0d5ecd)

Did you try with ES version?

**Comment by atago0129** [comment]
I'm sorry for the lack of confirmation.
I fixed bug on ES ( and fixed label size bug together...)

Now I checked on "Collapsible tree diagram in v4", and it looks like be ok.
![demo](https://user-images.githubusercontent.com/998831/43572505-ad9ce084-967a-11e8-8adf-2fad7328b480.gif)
( https://github.com/atago0129/d3-v4-contextmenu-demo )

**Comment by lmorel3** [comment]
You' a genius, I'm stupid.
I missed the fact that the **contextmenu** should be attached to a _node_, not to the whole _svg_. It works like a charm.

Thanks for your really quick answer/fix ;)

**Comment by atago0129** [comment]
I'm glad to hear that!
And now, I published npm package as v1.2.0.

Thanks too ;)
